/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_FmodEx_Init */

#ifndef _Included_org_jouvieje_FmodEx_Init
#define _Included_org_jouvieje_FmodEx_Init
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_FmodEx_Init
 * Method:    attachJavaVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodEx_Init_attachJavaVM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Init
 * Method:    get_PLATFORM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Init_get_1PLATFORM
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
