/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_FmodEx_Enumerations_EnumerationJNI */

#ifndef _Included_org_jouvieje_FmodEx_Enumerations_EnumerationJNI
#define _Included_org_jouvieje_FmodEx_Enumerations_EnumerationJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_UNKNOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1UNKNOWN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_MIXER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1MIXER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_OSCILLATOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1OSCILLATOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_LOWPASS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1LOWPASS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_ITLOWPASS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1ITLOWPASS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_HIGHPASS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1HIGHPASS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_ECHO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1ECHO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_FLANGE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1FLANGE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_DISTORTION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1DISTORTION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_NORMALIZE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1NORMALIZE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_PARAMEQ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1PARAMEQ
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_PITCHSHIFT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1PITCHSHIFT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_CHORUS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1CHORUS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_REVERB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1REVERB
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_VSTPLUGIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1VSTPLUGIN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_WINAMPPLUGIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1WINAMPPLUGIN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_ITECHO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1ITECHO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_COMPRESSOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1COMPRESSOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_SFXREVERB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1SFXREVERB
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_TYPE_LOWPASS_SIMPLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1TYPE_1LOWPASS_1SIMPLE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_OSCILLATOR_TYPE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1OSCILLATOR_1TYPE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_OSCILLATOR_RATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1OSCILLATOR_1RATE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_LOWPASS_CUTOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1LOWPASS_1CUTOFF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_LOWPASS_RESONANCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1LOWPASS_1RESONANCE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ITLOWPASS_CUTOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ITLOWPASS_1CUTOFF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ITLOWPASS_RESONANCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ITLOWPASS_1RESONANCE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_HIGHPASS_CUTOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1HIGHPASS_1CUTOFF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_HIGHPASS_RESONANCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1HIGHPASS_1RESONANCE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ECHO_DELAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ECHO_1DELAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ECHO_DECAYRATIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ECHO_1DECAYRATIO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ECHO_MAXCHANNELS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ECHO_1MAXCHANNELS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ECHO_DRYMIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ECHO_1DRYMIX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ECHO_WETMIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ECHO_1WETMIX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FLANGE_DRYMIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FLANGE_1DRYMIX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FLANGE_WETMIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FLANGE_1WETMIX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FLANGE_DEPTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FLANGE_1DEPTH
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FLANGE_RATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FLANGE_1RATE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_DISTORTION_LEVEL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1DISTORTION_1LEVEL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_NORMALIZE_FADETIME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1NORMALIZE_1FADETIME
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_NORMALIZE_THRESHHOLD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1NORMALIZE_1THRESHHOLD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_NORMALIZE_MAXAMP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1NORMALIZE_1MAXAMP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_PARAMEQ_CENTER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1PARAMEQ_1CENTER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_PARAMEQ_BANDWIDTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1PARAMEQ_1BANDWIDTH
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_PARAMEQ_GAIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1PARAMEQ_1GAIN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_PITCHSHIFT_PITCH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1PITCHSHIFT_1PITCH
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_PITCHSHIFT_FFTSIZE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1PITCHSHIFT_1FFTSIZE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_PITCHSHIFT_OVERLAP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1PITCHSHIFT_1OVERLAP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_PITCHSHIFT_MAXCHANNELS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1PITCHSHIFT_1MAXCHANNELS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_CHORUS_DRYMIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1CHORUS_1DRYMIX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_CHORUS_WETMIX1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1CHORUS_1WETMIX1
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_CHORUS_WETMIX2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1CHORUS_1WETMIX2
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_CHORUS_WETMIX3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1CHORUS_1WETMIX3
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_CHORUS_DELAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1CHORUS_1DELAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_CHORUS_RATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1CHORUS_1RATE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_CHORUS_DEPTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1CHORUS_1DEPTH
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_CHORUS_FEEDBACK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1CHORUS_1FEEDBACK
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_REVERB_ROOMSIZE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1REVERB_1ROOMSIZE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_REVERB_DAMP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1REVERB_1DAMP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_REVERB_WETMIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1REVERB_1WETMIX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_REVERB_DRYMIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1REVERB_1DRYMIX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_REVERB_WIDTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1REVERB_1WIDTH
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_REVERB_MODE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1REVERB_1MODE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ITECHO_WETDRYMIX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ITECHO_1WETDRYMIX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ITECHO_FEEDBACK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ITECHO_1FEEDBACK
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ITECHO_LEFTDELAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ITECHO_1LEFTDELAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ITECHO_RIGHTDELAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ITECHO_1RIGHTDELAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_ITECHO_PANDELAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1ITECHO_1PANDELAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_COMPRESSOR_THRESHOLD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1COMPRESSOR_1THRESHOLD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_COMPRESSOR_ATTACK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1COMPRESSOR_1ATTACK
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_COMPRESSOR_RELEASE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1COMPRESSOR_1RELEASE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_COMPRESSOR_GAINMAKEUP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1COMPRESSOR_1GAINMAKEUP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_DRYLEVEL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1DRYLEVEL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_ROOM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1ROOM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_ROOMHF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1ROOMHF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_ROOMROLLOFFFACTOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1ROOMROLLOFFFACTOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_DECAYTIME
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1DECAYTIME
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_DECAYHFRATIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1DECAYHFRATIO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_REFLECTIONSLEVEL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1REFLECTIONSLEVEL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_REFLECTIONSDELAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1REFLECTIONSDELAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_REVERBLEVEL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1REVERBLEVEL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_REVERBDELAY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1REVERBDELAY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_DIFFUSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1DIFFUSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_DENSITY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1DENSITY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_HFREFERENCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1HFREFERENCE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_ROOMLF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1ROOMLF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_SFXREVERB_LFREFERENCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1SFXREVERB_1LFREFERENCE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_LOWPASS_SIMPLE_CUTOFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1LOWPASS_1SIMPLE_1CUTOFF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OK
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_ALREADYLOCKED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1ALREADYLOCKED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_BADCOMMAND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1BADCOMMAND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CDDA_DRIVERS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CDDA_1DRIVERS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CDDA_INIT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CDDA_1INIT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CDDA_INVALID_DEVICE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CDDA_1INVALID_1DEVICE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CDDA_NOAUDIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CDDA_1NOAUDIO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CDDA_NODEVICES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CDDA_1NODEVICES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CDDA_NODISC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CDDA_1NODISC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CDDA_READ
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CDDA_1READ
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CHANNEL_ALLOC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CHANNEL_1ALLOC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_CHANNEL_STOLEN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1CHANNEL_1STOLEN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_COM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1COM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_DMA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1DMA
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_DSP_CONNECTION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1DSP_1CONNECTION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_DSP_FORMAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1DSP_1FORMAT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_DSP_NOTFOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1DSP_1NOTFOUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_DSP_RUNNING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1DSP_1RUNNING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_DSP_TOOMANYCONNECTIONS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1DSP_1TOOMANYCONNECTIONS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FILE_BAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FILE_1BAD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FILE_COULDNOTSEEK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FILE_1COULDNOTSEEK
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FILE_DISKEJECTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FILE_1DISKEJECTED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FILE_EOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FILE_1EOF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FILE_NOTFOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FILE_1NOTFOUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FILE_UNWANTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FILE_1UNWANTED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_FORMAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1FORMAT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_HTTP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1HTTP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_HTTP_ACCESS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1HTTP_1ACCESS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_HTTP_PROXY_AUTH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1HTTP_1PROXY_1AUTH
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_HTTP_SERVER_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1HTTP_1SERVER_1ERROR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_HTTP_TIMEOUT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1HTTP_1TIMEOUT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INITIALIZATION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INITIALIZATION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INITIALIZED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INITIALIZED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INTERNAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INTERNAL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INVALID_ADDRESS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INVALID_1ADDRESS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INVALID_FLOAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INVALID_1FLOAT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INVALID_HANDLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INVALID_1HANDLE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INVALID_PARAM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INVALID_1PARAM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INVALID_SPEAKER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INVALID_1SPEAKER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_INVALID_VECTOR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1INVALID_1VECTOR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_IRX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1IRX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_MAXAUDIBLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1MAXAUDIBLE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_MEMORY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1MEMORY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_MEMORY_CANTPOINT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1MEMORY_1CANTPOINT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_MEMORY_IOP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1MEMORY_1IOP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_MEMORY_SRAM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1MEMORY_1SRAM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NEEDS2D
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NEEDS2D
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NEEDS3D
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NEEDS3D
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NEEDSHARDWARE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NEEDSHARDWARE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NEEDSSOFTWARE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NEEDSSOFTWARE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NET_CONNECT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NET_1CONNECT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NET_SOCKET_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NET_1SOCKET_1ERROR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NET_URL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NET_1URL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NET_WOULD_BLOCK
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NET_1WOULD_1BLOCK
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_NOTREADY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1NOTREADY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_OUTPUT_ALLOCATED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1OUTPUT_1ALLOCATED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_OUTPUT_CREATEBUFFER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1OUTPUT_1CREATEBUFFER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_OUTPUT_DRIVERCALL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1OUTPUT_1DRIVERCALL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_OUTPUT_ENUMERATION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1OUTPUT_1ENUMERATION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_OUTPUT_FORMAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1OUTPUT_1FORMAT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_OUTPUT_INIT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1OUTPUT_1INIT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_OUTPUT_NOHARDWARE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1OUTPUT_1NOHARDWARE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_OUTPUT_NOSOFTWARE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1OUTPUT_1NOSOFTWARE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_PAN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1PAN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_PLUGIN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1PLUGIN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_PLUGIN_INSTANCES
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1PLUGIN_1INSTANCES
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_PLUGIN_MISSING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1PLUGIN_1MISSING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_PLUGIN_RESOURCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1PLUGIN_1RESOURCE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_RECORD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1RECORD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_REVERB_INSTANCE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1REVERB_1INSTANCE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_SUBSOUND_ALLOCATED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1SUBSOUND_1ALLOCATED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_SUBSOUND_CANTMOVE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1SUBSOUND_1CANTMOVE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_SUBSOUND_MODE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1SUBSOUND_1MODE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_SUBSOUNDS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1SUBSOUNDS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_TAGNOTFOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1TAGNOTFOUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_TOOMANYCHANNELS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1TOOMANYCHANNELS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_UNIMPLEMENTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1UNIMPLEMENTED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_UNINITIALIZED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1UNINITIALIZED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_UNSUPPORTED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1UNSUPPORTED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_UPDATE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1UPDATE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1VERSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_EVENT_FAILED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1EVENT_1FAILED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_EVENT_INFOONLY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1EVENT_1INFOONLY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_EVENT_INTERNAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1EVENT_1INTERNAL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_EVENT_MAXSTREAMS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1EVENT_1MAXSTREAMS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_EVENT_MISMATCH
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1EVENT_1MISMATCH
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_EVENT_NAMECONFLICT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1EVENT_1NAMECONFLICT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_ERR_EVENT_NOTFOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1ERR_1EVENT_1NOTFOUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_AUTODETECT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1AUTODETECT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_UNKNOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1UNKNOWN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_NOSOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1NOSOUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_WAVWRITER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1WAVWRITER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_NOSOUND_NRT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1NOSOUND_1NRT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_WAVWRITER_NRT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1WAVWRITER_1NRT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_DSOUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1DSOUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_WINMM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1WINMM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_OPENAL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1OPENAL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_WASAPI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1WASAPI
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_ASIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1ASIO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_OSS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1OSS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_ALSA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1ALSA
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_ESD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1ESD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_SOUNDMANAGER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1SOUNDMANAGER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_COREAUDIO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1COREAUDIO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_XBOX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1XBOX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_PS2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1PS2
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_PS3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1PS3
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_GC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1GC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_XBOX360
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1XBOX360
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_PSP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1PSP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_WII
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1WII
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OUTPUTTYPE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OUTPUTTYPE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMODE_RAW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMODE_1RAW
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMODE_MONO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMODE_1MONO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMODE_STEREO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMODE_1STEREO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMODE_QUAD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMODE_1QUAD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMODE_SURROUND
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMODE_1SURROUND
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMODE_5POINT1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMODE_15POINT1
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMODE_7POINT1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMODE_17POINT1
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMODE_PROLOGIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMODE_1PROLOGIC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMODE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMODE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_FRONT_LEFT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1FRONT_1LEFT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_FRONT_RIGHT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1FRONT_1RIGHT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_FRONT_CENTER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1FRONT_1CENTER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_LOW_FREQUENCY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1LOW_1FREQUENCY
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_BACK_LEFT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1BACK_1LEFT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_BACK_RIGHT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1BACK_1RIGHT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_SIDE_LEFT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1SIDE_1LEFT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_SIDE_RIGHT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1SIDE_1RIGHT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_MONO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1MONO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_NULL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1NULL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_SBL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1SBL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKER_SBR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKER_1SBR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_PLUGINTYPE_OUTPUT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1PLUGINTYPE_1OUTPUT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_PLUGINTYPE_CODEC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1PLUGINTYPE_1CODEC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_PLUGINTYPE_DSP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1PLUGINTYPE_1DSP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_PLUGINTYPE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1PLUGINTYPE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_UNKNOWN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1UNKNOWN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_AAC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1AAC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_AIFF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1AIFF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_ASF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1ASF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_AT3
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1AT3
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_CDDA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1CDDA
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_DLS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1DLS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_FLAC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1FLAC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_FSB
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1FSB
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_GCADPCM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1GCADPCM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_IT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1IT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_MIDI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1MIDI
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_MOD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1MOD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_MPEG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1MPEG
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_OGGVORBIS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1OGGVORBIS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_PLAYLIST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1PLAYLIST
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_RAW
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1RAW
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_S3M
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1S3M
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_SF2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1SF2
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_USER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1USER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_WAV
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1WAV
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_XM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1XM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_XMA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1XMA
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_VAG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1VAG
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_TYPE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1TYPE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_NONE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1NONE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_PCM8
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1PCM8
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_PCM16
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1PCM16
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_PCM24
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1PCM24
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_PCM32
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1PCM32
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_PCMFLOAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1PCMFLOAT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_GCADPCM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1GCADPCM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_IMAADPCM
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1IMAADPCM
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_VAG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1VAG
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_XMA
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1XMA
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_MPEG
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1MPEG
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUND_FORMAT_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUND_1FORMAT_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OPENSTATE_LOADING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OPENSTATE_1LOADING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OPENSTATE_ERROR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OPENSTATE_1ERROR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OPENSTATE_CONNECTING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OPENSTATE_1CONNECTING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OPENSTATE_BUFFERING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OPENSTATE_1BUFFERING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OPENSTATE_SEEKING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OPENSTATE_1SEEKING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OPENSTATE_STREAMING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OPENSTATE_1STREAMING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_OPENSTATE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1OPENSTATE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUNDGROUP_BEHAVIOR_FAIL
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUNDGROUP_1BEHAVIOR_1FAIL
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUNDGROUP_BEHAVIOR_MUTE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUNDGROUP_1BEHAVIOR_1MUTE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUNDGROUP_BEHAVIOR_STEALLOWEST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUNDGROUP_1BEHAVIOR_1STEALLOWEST
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SOUNDGROUP_BEHAVIOR_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SOUNDGROUP_1BEHAVIOR_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_CHANNEL_CALLBACKTYPE_END
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1CHANNEL_1CALLBACKTYPE_1END
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_CHANNEL_CALLBACKTYPE_VIRTUALVOICE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1CHANNEL_1CALLBACKTYPE_1VIRTUALVOICE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_CHANNEL_CALLBACKTYPE_SYNCPOINT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1CHANNEL_1CALLBACKTYPE_1SYNCPOINT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_CHANNEL_CALLBACKTYPE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1CHANNEL_1CALLBACKTYPE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SYSTEM_CALLBACKTYPE_DEVICELISTCHANGED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SYSTEM_1CALLBACKTYPE_1DEVICELISTCHANGED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SYSTEM_CALLBACKTYPE_MEMORYALLOCATIONFAILED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SYSTEM_1CALLBACKTYPE_1MEMORYALLOCATIONFAILED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SYSTEM_CALLBACKTYPE_THREADCREATED
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SYSTEM_1CALLBACKTYPE_1THREADCREATED
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SYSTEM_CALLBACKTYPE_BADDSPCONNECTION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SYSTEM_1CALLBACKTYPE_1BADDSPCONNECTION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SYSTEM_CALLBACKTYPE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SYSTEM_1CALLBACKTYPE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FFT_WINDOW_RECT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FFT_1WINDOW_1RECT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FFT_WINDOW_TRIANGLE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FFT_1WINDOW_1TRIANGLE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FFT_WINDOW_HAMMING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FFT_1WINDOW_1HAMMING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FFT_WINDOW_HANNING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FFT_1WINDOW_1HANNING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FFT_WINDOW_BLACKMAN
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FFT_1WINDOW_1BLACKMAN
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FFT_WINDOW_BLACKMANHARRIS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FFT_1WINDOW_1BLACKMANHARRIS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_FFT_WINDOW_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1FFT_1WINDOW_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_RESAMPLER_NOINTERP
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1RESAMPLER_1NOINTERP
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_RESAMPLER_LINEAR
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1RESAMPLER_1LINEAR
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_RESAMPLER_CUBIC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1RESAMPLER_1CUBIC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_RESAMPLER_SPLINE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1RESAMPLER_1SPLINE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DSP_RESAMPLER_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DSP_1RESAMPLER_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_ID3V1
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1ID3V1
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_ID3V2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1ID3V2
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_VORBISCOMMENT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1VORBISCOMMENT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_SHOUTCAST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1SHOUTCAST
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_ICECAST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1ICECAST
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_ASF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1ASF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_MIDI
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1MIDI
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_PLAYLIST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1PLAYLIST
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_FMOD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1FMOD
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_USER
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1USER
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGTYPE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGTYPE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGDATATYPE_INT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGDATATYPE_1INT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGDATATYPE_FLOAT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGDATATYPE_1FLOAT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGDATATYPE_STRING
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGDATATYPE_1STRING
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGDATATYPE_STRING_UTF16
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGDATATYPE_1STRING_1UTF16
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGDATATYPE_STRING_UTF16BE
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGDATATYPE_1STRING_1UTF16BE
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGDATATYPE_STRING_UTF8
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGDATATYPE_1STRING_1UTF8
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGDATATYPE_CDTOC
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGDATATYPE_1CDTOC
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_TAGDATATYPE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1TAGDATATYPE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DELAYTYPE_END_MS
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DELAYTYPE_1END_1MS
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DELAYTYPE_DSPCLOCK_START
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DELAYTYPE_1DSPCLOCK_1START
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DELAYTYPE_DSPCLOCK_END
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DELAYTYPE_1DSPCLOCK_1END
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_DELAYTYPE_MAX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1DELAYTYPE_1MAX
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMAPTYPE_DEFAULT
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMAPTYPE_1DEFAULT
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMAPTYPE_ALLMONO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMAPTYPE_1ALLMONO
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodEx_Enumerations_EnumerationJNI
 * Method:    get_FMOD_SPEAKERMAPTYPE_ALLSTEREO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_Enumerations_EnumerationJNI_get_1FMOD_1SPEAKERMAPTYPE_1ALLSTEREO
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
