/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_FmodEx_FmodExJNI */

#ifndef _Included_org_jouvieje_FmodEx_FmodExJNI
#define _Included_org_jouvieje_FmodEx_FmodExJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    FMOD_ErrorString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_FMOD_1ErrorString
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    getHwnd
 * Signature: (Ljava/awt/Component;)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_getHwnd
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    FmodEx_Memory_Initialize
 * Signature: (Ljava/nio/ByteBuffer;JIZZZI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_FmodEx_1Memory_1Initialize
  (JNIEnv *, jclass, jobject, jlong, jint, jboolean, jboolean, jboolean, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    FmodEx_Memory_GetStats
 * Signature: (Ljava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_FmodEx_1Memory_1GetStats
  (JNIEnv *, jclass, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    FmodEx_Debug_SetLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_FmodEx_1Debug_1SetLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    FmodEx_Debug_GetLevel
 * Signature: (Ljava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_FmodEx_1Debug_1GetLevel
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    FmodEx_File_SetDiskBusy
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_FmodEx_1File_1SetDiskBusy
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    FmodEx_File_GetDiskBusy
 * Signature: (Ljava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_FmodEx_1File_1GetDiskBusy
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    FmodEx_System_Create
 * Signature: (Lorg/jouvieje/FmodEx/System;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_FmodEx_1System_1Create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setOutput
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setOutput
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getOutput
 * Signature: (JLjava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getOutput
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getNumDrivers
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getNumDrivers
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getDriverInfo
 * Signature: (JILjava/nio/ByteBuffer;JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getDriverInfo
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getDriverCaps
 * Signature: (JILjava/nio/IntBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getDriverCaps
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jobject, jlong, jobject, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setDriver
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setDriver
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getDriver
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getDriver
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setHardwareChannels
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setHardwareChannels
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setSoftwareChannels
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setSoftwareChannels
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getSoftwareChannels
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getSoftwareChannels
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setSoftwareFormat
 * Signature: (JIIIII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setSoftwareFormat
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getSoftwareFormat
 * Signature: (JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;Ljava/nio/IntBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;Ljava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getSoftwareFormat
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jobject, jlong, jobject, jlong, jobject, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setDSPBufferSize
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setDSPBufferSize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getDSPBufferSize
 * Signature: (JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getDSPBufferSize
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setFileSystem
 * Signature: (JZZZZI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setFileSystem
  (JNIEnv *, jclass, jlong, jboolean, jboolean, jboolean, jboolean, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_attachFileSystem
 * Signature: (JZZZZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1attachFileSystem
  (JNIEnv *, jclass, jlong, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setAdvancedSettings
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setAdvancedSettings
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getAdvancedSettings
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getAdvancedSettings
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setSpeakerMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setSpeakerMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getSpeakerMode
 * Signature: (JLjava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getSpeakerMode
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setCallback
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setCallback
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setPluginPath
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setPluginPath
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_loadPlugin
 * Signature: (J[BLjava/nio/IntBuffer;Ljava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1loadPlugin
  (JNIEnv *, jclass, jlong, jbyteArray, jobject, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getNumPlugins
 * Signature: (JILjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getNumPlugins
  (JNIEnv *, jclass, jlong, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getPluginInfo
 * Signature: (JIILjava/nio/ByteBuffer;JILjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getPluginInfo
  (JNIEnv *, jclass, jlong, jint, jint, jobject, jlong, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_unloadPlugin
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1unloadPlugin
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setOutputByPlugin
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setOutputByPlugin
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getOutputByPlugin
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getOutputByPlugin
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createCodec
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createCodec
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_init
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1init
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_update
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1update
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_set3DSettings
 * Signature: (JFFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1set3DSettings
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_get3DSettings
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1get3DSettings
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_set3DNumListeners
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1set3DNumListeners
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_get3DNumListeners
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1get3DNumListeners
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_set3DListenerAttributes
 * Signature: (JIJJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1set3DListenerAttributes
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_get3DListenerAttributes
 * Signature: (JIJJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1get3DListenerAttributes
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_set3DRolloffCallback
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1set3DRolloffCallback
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_set3DSpeakerPosition
 * Signature: (JIFFZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1set3DSpeakerPosition
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_get3DSpeakerPosition
 * Signature: (JILjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1get3DSpeakerPosition
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setStreamBufferSize
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setStreamBufferSize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getStreamBufferSize
 * Signature: (JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getStreamBufferSize
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getVersion
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getVersion
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getOutputHandle
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getOutputHandle
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getChannelsPlaying
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getChannelsPlaying
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getHardwareChannels
 * Signature: (JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getHardwareChannels
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getCPUUsage
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getCPUUsage
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getSoundRAM
 * Signature: (JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getSoundRAM
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getNumCDROMDrives
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getNumCDROMDrives
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getCDROMDriveName
 * Signature: (JILjava/nio/ByteBuffer;JILjava/nio/ByteBuffer;JILjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getCDROMDriveName
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jint, jobject, jlong, jint, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getSpectrum
 * Signature: (JLjava/nio/FloatBuffer;JIII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getSpectrum
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getWaveData
 * Signature: (JLjava/nio/FloatBuffer;JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getWaveData
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createSound
 * Signature: (J[BIJLorg/jouvieje/FmodEx/Sound;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createSound__J_3BIJLorg_jouvieje_FmodEx_Sound_2
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createSound
 * Signature: (JLjava/nio/ByteBuffer;JIJLorg/jouvieje/FmodEx/Sound;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createSound__JLjava_nio_ByteBuffer_2JIJLorg_jouvieje_FmodEx_Sound_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createStream
 * Signature: (J[BIJLorg/jouvieje/FmodEx/Sound;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createStream__J_3BIJLorg_jouvieje_FmodEx_Sound_2
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createStream
 * Signature: (JLjava/nio/ByteBuffer;JIJLorg/jouvieje/FmodEx/Sound;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createStream__JLjava_nio_ByteBuffer_2JIJLorg_jouvieje_FmodEx_Sound_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createDSP
 * Signature: (JJLorg/jouvieje/FmodEx/DSP;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createDSP
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createDSPByType
 * Signature: (JILorg/jouvieje/FmodEx/DSP;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createDSPByType
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createDSPByIndex
 * Signature: (JILorg/jouvieje/FmodEx/DSP;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createDSPByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createChannelGroup
 * Signature: (J[BLorg/jouvieje/FmodEx/ChannelGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createChannelGroup
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createSoundGroup
 * Signature: (J[BLorg/jouvieje/FmodEx/SoundGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createSoundGroup
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createReverb
 * Signature: (JLorg/jouvieje/FmodEx/Reverb;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createReverb
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_playSound
 * Signature: (JIJZLorg/jouvieje/FmodEx/Channel;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1playSound
  (JNIEnv *, jclass, jlong, jint, jlong, jboolean, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_playDSP
 * Signature: (JIJZLorg/jouvieje/FmodEx/Channel;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1playDSP
  (JNIEnv *, jclass, jlong, jint, jlong, jboolean, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getChannel
 * Signature: (JILorg/jouvieje/FmodEx/Channel;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getChannel
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getMasterChannelGroup
 * Signature: (JLorg/jouvieje/FmodEx/ChannelGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getMasterChannelGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getMasterSoundGroup
 * Signature: (JLorg/jouvieje/FmodEx/SoundGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getMasterSoundGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setReverbAmbientProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setReverbAmbientProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getReverbAmbientProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getReverbAmbientProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getDSPHead
 * Signature: (JLorg/jouvieje/FmodEx/DSP;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getDSPHead
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_addDSP
 * Signature: (JJLorg/jouvieje/FmodEx/DSPConnection;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1addDSP
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_lockDSP
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1lockDSP
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_unlockDSP
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1unlockDSP
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getDSPClock
 * Signature: (JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getDSPClock
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setRecordDriver
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setRecordDriver
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getRecordDriver
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getRecordDriver
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getRecordNumDrivers
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getRecordNumDrivers
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getRecordDriverInfo
 * Signature: (JILjava/nio/ByteBuffer;JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getRecordDriverInfo
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getRecordDriverCaps
 * Signature: (JILjava/nio/IntBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getRecordDriverCaps
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getRecordPosition
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getRecordPosition
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_recordStart
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1recordStart
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_recordStop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1recordStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_isRecording
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1isRecording
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_createGeometry
 * Signature: (JIILorg/jouvieje/FmodEx/Geometry;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1createGeometry
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setGeometrySettings
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setGeometrySettings
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getGeometrySettings
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getGeometrySettings
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_loadGeometry
 * Signature: (JLjava/nio/ByteBuffer;JILorg/jouvieje/FmodEx/Geometry;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1loadGeometry
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setNetworkProxy
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setNetworkProxy
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getNetworkProxy
 * Signature: (JLjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getNetworkProxy
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setNetworkTimeout
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setNetworkTimeout
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getNetworkTimeout
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getNetworkTimeout
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    System_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_System_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getSystemObject
 * Signature: (JLorg/jouvieje/FmodEx/System;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getSystemObject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_lock
 * Signature: (JII[Ljava/nio/ByteBuffer;[Ljava/nio/ByteBuffer;Ljava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1lock
  (JNIEnv *, jclass, jlong, jint, jint, jobjectArray, jobjectArray, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_unlock
 * Signature: (JLjava/nio/ByteBuffer;JLjava/nio/ByteBuffer;JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1unlock
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setDefaults
 * Signature: (JFFFI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setDefaults
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getDefaults
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getDefaults
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setVariations
 * Signature: (JFFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setVariations
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getVariations
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getVariations
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_set3DMinMaxDistance
 * Signature: (JFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1set3DMinMaxDistance
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_get3DMinMaxDistance
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1get3DMinMaxDistance
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_set3DConeSettings
 * Signature: (JFFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1set3DConeSettings
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_get3DConeSettings
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1get3DConeSettings
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_set3DCustomRolloff
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1set3DCustomRolloff
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_get3DCustomRolloff
 * Signature: (JLorg/jouvieje/FmodEx/Structures/FMOD_VECTOR;Ljava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1get3DCustomRolloff
  (JNIEnv *, jclass, jlong, jobject, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setSubSound
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setSubSound
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getSubSound
 * Signature: (JILorg/jouvieje/FmodEx/Sound;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getSubSound
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setSubSoundSentence
 * Signature: (JLjava/nio/IntBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setSubSoundSentence
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getName
 * Signature: (JLjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getName
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getLength
 * Signature: (JLjava/nio/IntBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getLength
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getFormat
 * Signature: (JLjava/nio/IntBuffer;Ljava/nio/IntBuffer;Ljava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getFormat
  (JNIEnv *, jclass, jlong, jobject, jobject, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getNumSubSounds
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getNumSubSounds
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getNumTags
 * Signature: (JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getNumTags
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getTag
 * Signature: (J[BIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getTag
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getOpenState
 * Signature: (JLjava/nio/IntBuffer;Ljava/nio/IntBuffer;JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getOpenState
  (JNIEnv *, jclass, jlong, jobject, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_readData
 * Signature: (JLjava/nio/ByteBuffer;JILjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1readData
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_seekData
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1seekData
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setSoundGroup
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setSoundGroup
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getSoundGroup
 * Signature: (JLorg/jouvieje/FmodEx/SoundGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getSoundGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getNumSyncPoints
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getNumSyncPoints
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getSyncPoint
 * Signature: (JILorg/jouvieje/FmodEx/Structures/FMOD_SYNCPOINT;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getSyncPoint
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getSyncPointInfo
 * Signature: (JJLjava/nio/ByteBuffer;JILjava/nio/IntBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getSyncPointInfo
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jint, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_addSyncPoint
 * Signature: (JII[BLorg/jouvieje/FmodEx/Structures/FMOD_SYNCPOINT;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1addSyncPoint
  (JNIEnv *, jclass, jlong, jint, jint, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_deleteSyncPoint
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1deleteSyncPoint
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getMode
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getMode
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setLoopCount
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setLoopCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getLoopCount
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getLoopCount
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setLoopPoints
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setLoopPoints
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getLoopPoints
 * Signature: (JLjava/nio/IntBuffer;JILjava/nio/IntBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getLoopPoints
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getMusicNumChannels
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getMusicNumChannels
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setMusicChannelVolume
 * Signature: (JIF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setMusicChannelVolume
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getMusicChannelVolume
 * Signature: (JILjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getMusicChannelVolume
  (JNIEnv *, jclass, jlong, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Sound_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Sound_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getSystemObject
 * Signature: (JLorg/jouvieje/FmodEx/System;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getSystemObject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setPaused
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getPaused
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getPaused
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getVolume
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getVolume
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setFrequency
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setFrequency
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getFrequency
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getFrequency
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setPan
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setPan
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getPan
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getPan
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setDelay
 * Signature: (JIII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setDelay
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getDelay
 * Signature: (JILjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getDelay
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setSpeakerMix
 * Signature: (JFFFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setSpeakerMix
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getSpeakerMix
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getSpeakerMix
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setSpeakerLevels
 * Signature: (JILjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setSpeakerLevels
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getSpeakerLevels
 * Signature: (JILjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getSpeakerLevels
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setInputChannelMix
 * Signature: (JLjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setInputChannelMix
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getInputChannelMix
 * Signature: (JLjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getInputChannelMix
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setMute
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setMute
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getMute
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getMute
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setPriority
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setPriority
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getPriority
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getPriority
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setPosition
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setPosition
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getPosition
 * Signature: (JLjava/nio/IntBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getPosition
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setChannelGroup
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setChannelGroup
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getChannelGroup
 * Signature: (JLorg/jouvieje/FmodEx/ChannelGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getChannelGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setCallback
 * Signature: (JIZI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setCallback
  (JNIEnv *, jclass, jlong, jint, jboolean, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_set3DAttributes
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1set3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_get3DAttributes
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1get3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_set3DMinMaxDistance
 * Signature: (JFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1set3DMinMaxDistance
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_get3DMinMaxDistance
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1get3DMinMaxDistance
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_set3DConeSettings
 * Signature: (JFFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1set3DConeSettings
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_get3DConeSettings
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1get3DConeSettings
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_set3DConeOrientation
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1set3DConeOrientation
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_get3DConeOrientation
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1get3DConeOrientation
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_set3DCustomRolloff
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1set3DCustomRolloff
  (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_get3DCustomRolloff
 * Signature: (JLorg/jouvieje/FmodEx/Structures/FMOD_VECTOR;Ljava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1get3DCustomRolloff
  (JNIEnv *, jclass, jlong, jobject, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_set3DOcclusion
 * Signature: (JFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1set3DOcclusion
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_get3DOcclusion
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1get3DOcclusion
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_set3DSpread
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1set3DSpread
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_get3DSpread
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1get3DSpread
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_set3DPanLevel
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1set3DPanLevel
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_get3DPanLevel
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1get3DPanLevel
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_set3DDopplerLevel
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1set3DDopplerLevel
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_get3DDopplerLevel
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1get3DDopplerLevel
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getDSPHead
 * Signature: (JLorg/jouvieje/FmodEx/DSP;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getDSPHead
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_addDSP
 * Signature: (JJLorg/jouvieje/FmodEx/DSPConnection;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1addDSP
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_isPlaying
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1isPlaying
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_isVirtual
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1isVirtual
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getAudibility
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getAudibility
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getCurrentSound
 * Signature: (JLorg/jouvieje/FmodEx/Sound;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getCurrentSound
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getSpectrum
 * Signature: (JLjava/nio/FloatBuffer;JIII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getSpectrum
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getWaveData
 * Signature: (JLjava/nio/FloatBuffer;JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getWaveData
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getIndex
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getIndex
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getMode
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getMode
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setLoopCount
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setLoopCount
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getLoopCount
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getLoopCount
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setLoopPoints
 * Signature: (JIIII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setLoopPoints
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getLoopPoints
 * Signature: (JLjava/nio/IntBuffer;JILjava/nio/IntBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getLoopPoints
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Channel_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Channel_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getSystemObject
 * Signature: (JLorg/jouvieje/FmodEx/System;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getSystemObject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getVolume
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getVolume
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_setPitch
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1setPitch
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getPitch
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getPitch
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_set3DOcclusion
 * Signature: (JFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1set3DOcclusion
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_get3DOcclusion
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1get3DOcclusion
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_setPaused
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1setPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getPaused
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getPaused
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_setMute
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1setMute
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getMute
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getMute
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_overrideVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1overrideVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_overrideFrequency
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1overrideFrequency
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_overridePan
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1overridePan
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_overrideReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1overrideReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_override3DAttributes
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1override3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_overrideSpeakerMix
 * Signature: (JFFFFFFFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1overrideSpeakerMix
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_addGroup
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1addGroup
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getNumGroups
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getNumGroups
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getGroup
 * Signature: (JILorg/jouvieje/FmodEx/ChannelGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getGroup
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getParentGroup
 * Signature: (JLorg/jouvieje/FmodEx/ChannelGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getParentGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getDSPHead
 * Signature: (JLorg/jouvieje/FmodEx/DSP;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getDSPHead
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_addDSP
 * Signature: (JJLorg/jouvieje/FmodEx/DSPConnection;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1addDSP
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getName
 * Signature: (JLjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getName
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getNumChannels
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getNumChannels
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getChannel
 * Signature: (JILorg/jouvieje/FmodEx/Channel;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getChannel
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getSpectrum
 * Signature: (JLjava/nio/FloatBuffer;JIII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getSpectrum
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getWaveData
 * Signature: (JLjava/nio/FloatBuffer;JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getWaveData
  (JNIEnv *, jclass, jlong, jobject, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    ChannelGroup_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_ChannelGroup_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getSystemObject
 * Signature: (JLorg/jouvieje/FmodEx/System;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getSystemObject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_setMaxAudible
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1setMaxAudible
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getMaxAudible
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getMaxAudible
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_setMaxAudibleBehavior
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1setMaxAudibleBehavior
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getMaxAudibleBehavior
 * Signature: (JLjava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getMaxAudibleBehavior
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_setMuteFadeSpeed
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1setMuteFadeSpeed
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getMuteFadeSpeed
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getMuteFadeSpeed
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getVolume
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getVolume
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_stop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1stop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getName
 * Signature: (JLjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getName
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getNumSounds
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getNumSounds
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getSound
 * Signature: (JILorg/jouvieje/FmodEx/Sound;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getSound
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getNumPlaying
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getNumPlaying
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    SoundGroup_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_SoundGroup_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getSystemObject
 * Signature: (JLorg/jouvieje/FmodEx/System;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getSystemObject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_addInput
 * Signature: (JJLorg/jouvieje/FmodEx/DSPConnection;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1addInput
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_disconnectFrom
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1disconnectFrom
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_disconnectAll
 * Signature: (JZZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1disconnectAll
  (JNIEnv *, jclass, jlong, jboolean, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_remove
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1remove
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getNumInputs
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getNumInputs
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getNumOutputs
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getNumOutputs
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getInput
 * Signature: (JILorg/jouvieje/FmodEx/DSP;Lorg/jouvieje/FmodEx/DSPConnection;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getInput
  (JNIEnv *, jclass, jlong, jint, jobject, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getOutput
 * Signature: (JILorg/jouvieje/FmodEx/DSP;Lorg/jouvieje/FmodEx/DSPConnection;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getOutput
  (JNIEnv *, jclass, jlong, jint, jobject, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_setActive
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1setActive
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getActive
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getActive
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_setBypass
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1setBypass
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getBypass
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getBypass
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_setSpeakerActive
 * Signature: (JIZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1setSpeakerActive
  (JNIEnv *, jclass, jlong, jint, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getSpeakerActive
 * Signature: (JILjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getSpeakerActive
  (JNIEnv *, jclass, jlong, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_setParameter
 * Signature: (JIF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1setParameter
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getParameter
 * Signature: (JILjava/nio/FloatBuffer;JLjava/nio/ByteBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getParameter
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getNumParameters
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getNumParameters
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getParameterInfo
 * Signature: (JILjava/nio/ByteBuffer;JLjava/nio/ByteBuffer;JLjava/nio/ByteBuffer;JILjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getParameterInfo
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jobject, jlong, jobject, jlong, jint, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_showConfigDialog
 * Signature: (JLjava/awt/Component;JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1showConfigDialog
  (JNIEnv *, jclass, jlong, jobject, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getInfo
 * Signature: (JLjava/nio/ByteBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getType
 * Signature: (JLjava/nio/IntBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getType
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_setDefaults
 * Signature: (JFFFI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1setDefaults
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jfloat, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getDefaults
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getDefaults
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSP_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSP_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSPConnection_getInput
 * Signature: (JLorg/jouvieje/FmodEx/DSP;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSPConnection_1getInput
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSPConnection_getOutput
 * Signature: (JLorg/jouvieje/FmodEx/DSP;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSPConnection_1getOutput
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSPConnection_setMix
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSPConnection_1setMix
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSPConnection_getMix
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSPConnection_1getMix
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSPConnection_setLevels
 * Signature: (JILjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSPConnection_1setLevels
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSPConnection_getLevels
 * Signature: (JILjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSPConnection_1getLevels
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSPConnection_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSPConnection_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    DSPConnection_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_DSPConnection_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_addPolygon
 * Signature: (JFFZIJLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1addPolygon
  (JNIEnv *, jclass, jlong, jfloat, jfloat, jboolean, jint, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getNumPolygons
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getNumPolygons
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getMaxPolygons
 * Signature: (JLjava/nio/IntBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getMaxPolygons
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getPolygonNumVertices
 * Signature: (JILjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getPolygonNumVertices
  (JNIEnv *, jclass, jlong, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_setPolygonVertex
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1setPolygonVertex
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getPolygonVertex
 * Signature: (JIIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getPolygonVertex
  (JNIEnv *, jclass, jlong, jint, jint, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_setPolygonAttributes
 * Signature: (JIFFZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1setPolygonAttributes
  (JNIEnv *, jclass, jlong, jint, jfloat, jfloat, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getPolygonAttributes
 * Signature: (JILjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getPolygonAttributes
  (JNIEnv *, jclass, jlong, jint, jobject, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_setActive
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1setActive
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getActive
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getActive
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_setRotation
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1setRotation
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getRotation
 * Signature: (JJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getRotation
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_setPosition
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1setPosition
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getPosition
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getPosition
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_setScale
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1setScale
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getScale
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getScale
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_save
 * Signature: (JLjava/nio/ByteBuffer;JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1save
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Geometry_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Geometry_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Reverb_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Reverb_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Reverb_set3DAttributes
 * Signature: (JJFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Reverb_1set3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Reverb_get3DAttributes
 * Signature: (JJLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Reverb_1get3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Reverb_setProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Reverb_1setProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Reverb_getProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Reverb_1getProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Reverb_setActive
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Reverb_1setActive
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Reverb_getActive
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Reverb_1getActive
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Reverb_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Reverb_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodEx_FmodExJNI
 * Method:    Reverb_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodEx_FmodExJNI_Reverb_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif
