/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_FmodDesigner_FmodDesignerJNI */

#ifndef _Included_org_jouvieje_FmodDesigner_FmodDesignerJNI
#define _Included_org_jouvieje_FmodDesigner_FmodDesignerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    FmodDesigner_EventSystem_Create
 * Signature: (Lorg/jouvieje/FmodDesigner/EventSystem;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_FmodDesigner_1EventSystem_1Create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    FmodDesigner_NetEventSystem_Init
 * Signature: (JS)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_FmodDesigner_1NetEventSystem_1Init
  (JNIEnv *, jclass, jlong, jshort);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    FmodDesigner_NetEventSystem_Update
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_FmodDesigner_1NetEventSystem_1Update
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    FmodDesigner_NetEventSystem_Shutdown
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_FmodDesigner_1NetEventSystem_1Shutdown
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    FmodDesigner_NetEventSystem_GetVersion
 * Signature: (Ljava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_FmodDesigner_1NetEventSystem_1GetVersion
  (JNIEnv *, jclass, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_init
 * Signature: (JIIJI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1init
  (JNIEnv *, jclass, jlong, jint, jint, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_update
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1update
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_setMediaPath
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1setMediaPath
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_setPluginPath
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1setPluginPath
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getVersion
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getVersion
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getInfo
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getInfo
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getSystemObject
 * Signature: (JLorg/jouvieje/FmodEx/System;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getSystemObject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getMusicSystem
 * Signature: (JLorg/jouvieje/FmodDesigner/MusicSystem;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getMusicSystem
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_load
 * Signature: (J[BJLorg/jouvieje/FmodDesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1load__J_3BJLorg_jouvieje_FmodDesigner_EventProject_2
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_load
 * Signature: (JLjava/nio/ByteBuffer;JJLorg/jouvieje/FmodDesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1load__JLjava_nio_ByteBuffer_2JJLorg_jouvieje_FmodDesigner_EventProject_2
  (JNIEnv *, jclass, jlong, jobject, jlong, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_unload
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1unload
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getProject
 * Signature: (J[BLorg/jouvieje/FmodDesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getProject
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getProjectByIndex
 * Signature: (JILorg/jouvieje/FmodDesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getProjectByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getNumProjects
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getNumProjects
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getCategory
 * Signature: (J[BLorg/jouvieje/FmodDesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getCategory
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getCategoryByIndex
 * Signature: (JILorg/jouvieje/FmodDesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getCategoryByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getNumCategories
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getNumCategories
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getGroup
 * Signature: (J[BZLorg/jouvieje/FmodDesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getGroup
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getEvent
 * Signature: (J[BILorg/jouvieje/FmodDesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getEvent
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getEventBySystemID
 * Signature: (JIILorg/jouvieje/FmodDesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getEventBySystemID
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getNumEvents
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getNumEvents
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_setReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1setReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getReverbPreset
 * Signature: (J[BJLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getReverbPreset
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getReverbPresetByIndex
 * Signature: (JIJLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getReverbPresetByIndex
  (JNIEnv *, jclass, jlong, jint, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getNumReverbPresets
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getNumReverbPresets
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_createReverb
 * Signature: (JLorg/jouvieje/FmodDesigner/EventReverb;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1createReverb
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_setReverbAmbientProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1setReverbAmbientProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getReverbAmbientProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getReverbAmbientProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_set3DNumListeners
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1set3DNumListeners
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_get3DNumListeners
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1get3DNumListeners
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_set3DListenerAttributes
 * Signature: (JIJJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1set3DListenerAttributes
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_get3DListenerAttributes
 * Signature: (JIJJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1get3DListenerAttributes
  (JNIEnv *, jclass, jlong, jint, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_registerMemoryFSB
 * Signature: (J[BJIZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1registerMemoryFSB
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jint, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventSystem_unregisterMemoryFSB
 * Signature: (J[B)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventSystem_1unregisterMemoryFSB
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_getGroup
 * Signature: (J[BZLorg/jouvieje/FmodDesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1getGroup
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_getGroupByIndex
 * Signature: (JIZLorg/jouvieje/FmodDesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1getGroupByIndex
  (JNIEnv *, jclass, jlong, jint, jboolean, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_getNumGroups
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1getNumGroups
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_getEvent
 * Signature: (J[BILorg/jouvieje/FmodDesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1getEvent
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_getEventByProjectID
 * Signature: (JIILorg/jouvieje/FmodDesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1getEventByProjectID
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_getNumEvents
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1getNumEvents
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventProject_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventProject_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_loadEventData
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1loadEventData
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_freeEventData
 * Signature: (JJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1freeEventData
  (JNIEnv *, jclass, jlong, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getGroup
 * Signature: (J[BZLorg/jouvieje/FmodDesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getGroup
  (JNIEnv *, jclass, jlong, jbyteArray, jboolean, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getGroupByIndex
 * Signature: (JIZLorg/jouvieje/FmodDesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getGroupByIndex
  (JNIEnv *, jclass, jlong, jint, jboolean, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getParentGroup
 * Signature: (JLorg/jouvieje/FmodDesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getParentGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getParentProject
 * Signature: (JLorg/jouvieje/FmodDesigner/EventProject;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getParentProject
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getNumGroups
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getNumGroups
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getEvent
 * Signature: (J[BILorg/jouvieje/FmodDesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getEvent
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getEventByIndex
 * Signature: (JIILorg/jouvieje/FmodDesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getEventByIndex
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getNumEvents
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getNumEvents
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getProperty
 * Signature: (J[BJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getProperty
  (JNIEnv *, jclass, jlong, jbyteArray, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getPropertyByIndex
 * Signature: (JIJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getPropertyByIndex
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getNumProperties
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getNumProperties
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getState
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getState
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventGroup_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventGroup_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getCategory
 * Signature: (J[BLorg/jouvieje/FmodDesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getCategory
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getCategoryByIndex
 * Signature: (JILorg/jouvieje/FmodDesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getCategoryByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getNumCategories
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getNumCategories
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getEventByIndex
 * Signature: (JIILorg/jouvieje/FmodDesigner/Event;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getEventByIndex
  (JNIEnv *, jclass, jlong, jint, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getNumEvents
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getNumEvents
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_stopAllEvents
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1stopAllEvents
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getVolume
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getVolume
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_setPitch
 * Signature: (JFI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1setPitch
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getPitch
 * Signature: (JLjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getPitch
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_setPaused
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1setPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getPaused
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getPaused
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_setMute
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1setMute
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getMute
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getMute
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getChannelGroup
 * Signature: (JLorg/jouvieje/FmodEx/ChannelGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getChannelGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventCategory_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventCategory_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_SIZEOF
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1SIZEOF
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_newArray
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1newArray
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_start
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1start
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_stop
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1stop
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/FmodEx/Misc/Pointer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getState
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getState
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getParentGroup
 * Signature: (JLorg/jouvieje/FmodDesigner/EventGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getParentGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getChannelGroup
 * Signature: (JLorg/jouvieje/FmodEx/ChannelGroup;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getChannelGroup
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_setCallback
 * Signature: (JZJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1setCallback
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getParameter
 * Signature: (J[BLorg/jouvieje/FmodDesigner/EventParameter;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getParameter
  (JNIEnv *, jclass, jlong, jbyteArray, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getParameterByIndex
 * Signature: (JILorg/jouvieje/FmodDesigner/EventParameter;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getParameterByIndex
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getNumParameters
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getNumParameters
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getProperty
 * Signature: (J[BJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getProperty
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getPropertyByIndex
 * Signature: (JIJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getPropertyByIndex
  (JNIEnv *, jclass, jlong, jint, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_setProperty
 * Signature: (J[BJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1setProperty
  (JNIEnv *, jclass, jlong, jbyteArray, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_setPropertyByIndex
 * Signature: (JIJZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1setPropertyByIndex
  (JNIEnv *, jclass, jlong, jint, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getNumProperties
 * Signature: (JLjava/nio/IntBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getNumProperties
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getCategory
 * Signature: (JLorg/jouvieje/FmodDesigner/EventCategory;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getCategory
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getVolume
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getVolume
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_setPitch
 * Signature: (JFI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1setPitch
  (JNIEnv *, jclass, jlong, jfloat, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getPitch
 * Signature: (JLjava/nio/FloatBuffer;JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getPitch
  (JNIEnv *, jclass, jlong, jobject, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_setPaused
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1setPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getPaused
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getPaused
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_setMute
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1setMute
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getMute
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getMute
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_set3DAttributes
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1set3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_get3DAttributes
 * Signature: (JJJJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1get3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_set3DOcclusion
 * Signature: (JFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1set3DOcclusion
  (JNIEnv *, jclass, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_get3DOcclusion
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1get3DOcclusion
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_setReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1setReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getReverbProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getReverbProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    Event_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_Event_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_getInfo
 * Signature: (JLjava/nio/IntBuffer;JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1getInfo
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_getRange
 * Signature: (JLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1getRange
  (JNIEnv *, jclass, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_setValue
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1setValue
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_getValue
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1getValue
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_setVelocity
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1setVelocity
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_getVelocity
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1getVelocity
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_setSeekSpeed
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1setSeekSpeed
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_getSeekSpeed
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1getSeekSpeed
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventParameter_keyOff
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventParameter_1keyOff
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventReverb_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventReverb_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventReverb_set3DAttributes
 * Signature: (JJFF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventReverb_1set3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jfloat, jfloat);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventReverb_get3DAttributes
 * Signature: (JJLjava/nio/FloatBuffer;JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventReverb_1get3DAttributes
  (JNIEnv *, jclass, jlong, jlong, jobject, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventReverb_setProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventReverb_1setProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventReverb_getProperties
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventReverb_1getProperties
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventReverb_setActive
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventReverb_1setActive
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventReverb_getActive
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventReverb_1getActive
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventReverb_setUserData
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventReverb_1setUserData
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    EventReverb_getUserData
 * Signature: (JLorg/jouvieje/FmodEx/Misc/Pointer;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_EventReverb_1getUserData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_reset
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_setVolume
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1setVolume
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_getVolume
 * Signature: (JLjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1getVolume
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_setPaused
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1setPaused
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_getPaused
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1getPaused
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_setMute
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1setMute
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_getMute
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1getMute
  (JNIEnv *, jclass, jlong, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_promptCue
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1promptCue
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_prepareCue
 * Signature: (JILorg/jouvieje/FmodDesigner/MusicPrompt;)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1prepareCue
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_getParameter
 * Signature: (JILjava/nio/FloatBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1getParameter
  (JNIEnv *, jclass, jlong, jint, jobject, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_setParameter
 * Signature: (JIF)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1setParameter
  (JNIEnv *, jclass, jlong, jint, jfloat);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_loadSoundData
 * Signature: (JII)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1loadSoundData
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_freeSoundData
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1freeSoundData
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicSystem_setCallback
 * Signature: (JZJ)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicSystem_1setCallback
  (JNIEnv *, jclass, jlong, jboolean, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicPrompt_release
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicPrompt_1release
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicPrompt_begin
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicPrompt_1begin
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicPrompt_end
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicPrompt_1end
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_jouvieje_FmodDesigner_FmodDesignerJNI
 * Method:    MusicPrompt_isActive
 * Signature: (JLjava/nio/ByteBuffer;J)I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_FmodDesignerJNI_MusicPrompt_1isActive
  (JNIEnv *, jclass, jlong, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
