/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_FmodDesigner_Defines_DefineJNI */

#ifndef _Included_org_jouvieje_FmodDesigner_Defines_DefineJNI
#define _Included_org_jouvieje_FmodDesigner_Defines_DefineJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_FmodDesigner_Defines_DefineJNI
 * Method:    get_FMOD_EVENT_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_Defines_DefineJNI_get_1FMOD_1EVENT_1VERSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodDesigner_Defines_DefineJNI
 * Method:    get_FMOD_EVENT_NET_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_Defines_DefineJNI_get_1FMOD_1EVENT_1NET_1VERSION
  (JNIEnv *, jclass);

/*
 * Class:     org_jouvieje_FmodDesigner_Defines_DefineJNI
 * Method:    get_NATIVEFMODDESIGNER_VERSION
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_jouvieje_FmodDesigner_Defines_DefineJNI_get_1NATIVEFMODDESIGNER_1VERSION
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
