/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jouvieje_FmodDesigner_InitFmodDesigner */

#ifndef _Included_org_jouvieje_FmodDesigner_InitFmodDesigner
#define _Included_org_jouvieje_FmodDesigner_InitFmodDesigner
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jouvieje_FmodDesigner_InitFmodDesigner
 * Method:    attachJavaVM
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_jouvieje_FmodDesigner_InitFmodDesigner_attachJavaVM
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
